### ISSUE TITLE
Skater/goalie data

### ISSUE THREAD

**Issue by MichaelBluetooth** [Nickomang/NHLApi#2]
Could we make the skater/goalie data returned from the team skater stats endpoint be represented as an object instead of a long comma delimited string? In it's current form, API consumers will need to do extra work to parse the data. Something like this would be easier to work with:

`{
"Number": 15,
"Position": "C",
"Name": "R. Getzlaf",
"GamesPlayed": 77,
"Goals": 31,
"Assists": 56,
"Points": 87,
"PlusMinus": 28,
"PIM": 31,
"SOG": 204,
"TOI/G": "21:17",
"PP": 5,
"SH": 0,
"GWG": 7,
"OT": 1
}`

**Comment by Nickomang** [comment]
That's a pretty good idea; I agree it'll be much easier to consume that way. The current implementation was pretty much just to save as much time as possible. I'll work on it this afternoon.
